name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.4, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Remove package-lock.json (avoid lock file warning)
        run: |
          if [ -f package-lock.json ]; then
            rm package-lock.json
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build SDK
        run: yarn run clean && yarn run build

      - name: Test
        run: yarn run test
